#!/bin/sh

# Run Simple X Hotkey Daemon for keybindgs
pgrep -x sxhkd > /dev/null || sxhkd &
# Run jonabur's picom for transparency and node switching animations
picom --experimental-backend &
# Set Polybar
polybar example &
# Set Walpaper and colorscheme
wal -i ~/Images/initialD/takumi.jpg --saturate 0.9
# BSPWM configuration
bspc monitor -d 1 2 3 4 5 # Desktops
bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true
