#!/bin/sh

# Set keyboard layout to fr
setxkbmap fr &
# Load wallpaper
~/.config/feh/fehbg &
~/restart-ntp.sh &
# Run Simple X Hotkey Daemon for keybindgs
pgrep -x sxhkd > /dev/null || sxhkd &
# Run Pipewire for sound
pgrep -x pipewire > /dev/null || pipewire &
pgrep -x pipewire-pulse > /dev/null || pipewire-pulse &
pgrep -x trayer > /dev/null || trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --transparent true --tint 0x504945 &
# BSPWM configuration
bspc monitor -d I II III IV V VI VII VIII IX X
bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true
