syntax on "Activate syntax
set noerrorbells
set tabstop=4 "How many spaces when a tab is pressed
set softtabstop=4 "How many spaces to add at the 
set shiftwidth=4 "How many spaces when you indent something
set expandtab "Insert spaces as tab is pressed
set smartindent
set number relativenumber " Hybrid number
set colorcolumn=80
set nowrap
set ignorecase "If you put ignorecase and smartcase then it's case sensitive
set smartcase "only if it has a uppercase letter
set noswapfile
set nobackup
set undofile "Undo branches are stored in files
set undodir=$XDG_CACHE_HOME/vim/undo " that are stored there
set incsearch "Permit to move to the pattern while searching
set nohlsearch "Do no highlight all pattern matches
set cursorline
let mapleader = " " " leader key set to  space
set runtimepath+=$XDG_CONFIG_HOME/vim " Vim follow the XDG Base Dir Spec
set packpath^=$XDG_CONFIG_HOME/vim
set hidden " permit modification of multiple buffers
set nrformats+=alpha " increment also alpha with Ctrl+a and dec with Ctrl+x
" Netrw
let g:netrw_banner = 0 " No banner
let g:netrw_liststyle = 3 " Setting nerdtree like style
let g:netrw_browse_split = 3 " Open in new tab
let g:netrw_winsize = 25 " Setting size
" Open netrw with leader p
nnoremap <leader>p :Vexplore<CR>
" No F1 help
nnoremap <F1> <nop>
" Copy to clipboard
vmap <C-c> :w !xclip -sel clip<CR><CR>
nmap <C-c> :.w !xclip -sel clip<CR><CR>

" Using packager as my plugin manager following the Vim 8 way of managing
function! s:packager_init(packager) abort
    call a:packager.add('kristijanhusak/vim-packager', { 'type': 'opt' }) " Package manager
    call a:packager.add('morhetz/gruvbox', { 'type': 'start' }) " Colorscheme
    call a:packager.add('prabirshrestha/vim-lsp', { 'type': 'start' }) " LSP Client
    call a:packager.add('dense-analysis/ale', { 'type': 'start' }) " LSP Client for linting
    call a:packager.add('rhysd/vim-lsp-ale', { 'type': 'start' }) " Combine both
    call a:packager.add('puremourning/vimspector', { 'type': 'start' }) " DAP Client
endfunction
packadd vim-packager
call packager#setup(function('s:packager_init'))

" Colorscheme
colorscheme gruvbox
set background=dark

" File type plugin
filetype plugin indent on

" LSP Settings
setlocal omnifunc=lsp#complete
setlocal signcolumn=yes
let g:ale_change_sign_column_color = 1
let g:ale_lint_on_save = 1
nnoremap gd :LspDefinition<CR>
nnoremap gh :LspHover<CR>

" DAP Settings
let g:vimspector_enable_mappings = 'VISUAL_STUDIO' " Debug as in VSCode
let g:vimspector_install_gadgets = [] " No gadgets by default
